;;; doom-dashboard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from doom-dashboard.el

(register-definition-prefixes "doom-dashboard" '("doom-dashboard-"))

;;; End of scraped data

(provide 'doom-dashboard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; doom-dashboard-autoloads.el ends here
