;;; rbenv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from rbenv.el

(autoload 'rbenv-use-global "rbenv" "\
Activate rbenv’s global Ruby." t)
(autoload 'rbenv-use-corresponding "rbenv" "\
Search for .ruby-version and activate the corresponding Ruby." t)
(autoload 'rbenv-use "rbenv" "\
Activate a specified version of Ruby.

(fn RUBY-VERSION)" t)
(defvar global-rbenv-mode nil "\
Non-nil if Global Rbenv mode is enabled.
See the `global-rbenv-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-rbenv-mode'.")
(custom-autoload 'global-rbenv-mode "rbenv" nil)
(autoload 'global-rbenv-mode "rbenv" "\
use rbenv to configure the ruby version used by your Emacs.

This is a global minor mode.  If called interactively, toggle the
`Global Rbenv mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='global-rbenv-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "rbenv" '("rbenv"))

;;; End of scraped data

(provide 'rbenv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rbenv-autoloads.el ends here
