;;; region-occurrences-highlighter-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from region-occurrences-highlighter.el

(autoload 'region-occurrences-highlighter-mode "region-occurrences-highlighter" "\
Highlight the current region and its occurrences, a la Visual Code.

This is a minor mode.  If called interactively, toggle the
`Region-Occurrences-Highlighter mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `region-occurrences-highlighter-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-region-occurrences-highlighter-mode 'globalized-minor-mode t)
(defvar global-region-occurrences-highlighter-mode nil "\
Non-nil if Global Region-Occurrences-Highlighter mode is enabled.
See the `global-region-occurrences-highlighter-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-region-occurrences-highlighter-mode'.")
(custom-autoload 'global-region-occurrences-highlighter-mode "region-occurrences-highlighter" nil)
(autoload 'global-region-occurrences-highlighter-mode "region-occurrences-highlighter" "\
Toggle Region-Occurrences-Highlighter mode in all buffers.
With prefix ARG, enable Global Region-Occurrences-Highlighter mode if
ARG is positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Region-Occurrences-Highlighter mode is enabled in all buffers where
`region-occurrences-highlighter--turn-on-region-occurrences-highlighter-mode' would do it.

See `region-occurrences-highlighter-mode' for more information on
Region-Occurrences-Highlighter mode.

(fn &optional ARG)" t)
(register-definition-prefixes "region-occurrences-highlighter" '("region-occurrences-highlighter-"))

;;; End of scraped data

(provide 'region-occurrences-highlighter-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; region-occurrences-highlighter-autoloads.el ends here
