;;; Automatically generated by ‘recentf’ on Tue Jun 10 22:21:33 2025  -*- mode: emacs-lisp; lexical-binding: t -*-

(setq recentf-list
      '(
        "~/.config/emacs/README.md"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
