;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-emacs-unix -*-
;; Minibuffer history file, automatically generated by â€˜savehistâ€™.

(setq savehist-minibuffer-history-variables '(elpaca-manager--history minibuffer-history consult--buffer-history markdown-gfm-language-history file-name-history extended-command-history))
(setq elpaca-manager--history '("markdown-toc"))
(setq minibuffer-history '("markdown-toc MELPA"))
(setq consult--buffer-history '("README.mdøˆ€€‚" "init.eløˆ€€‚" "README.mdøˆ€€‚"))
(setq markdown-gfm-language-history '("bash" "emacs-lisp"))
(setq file-name-history '("~/.config/emacs/init.el" "~/.config/emacs/README.md"))
(setq extended-command-history '("markdown-open" "markdown-toc-generate-or-refresh-toc" "elpaca-manager" "elpaca-browse" "markdown-preview" "reader"))
(setq projectile-project-command-history '#s(hash-table test equal))
