;;; aweshell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from aweshell.el

(register-definition-prefixes "aweshell" '("aweshell-" "eshell"))


;;; Generated autoloads from eshell-did-you-mean.el

(autoload 'eshell-did-you-mean-setup "eshell-did-you-mean" "\
`eshell-did-you' setup.")
(register-definition-prefixes "eshell-did-you-mean" '("eshell-did-you-mean-"))


;;; Generated autoloads from eshell-prompt-extras.el

(register-definition-prefixes "eshell-prompt-extras" '("epe-"))


;;; Generated autoloads from eshell-up.el

(autoload 'eshell-up "eshell-up" "\
Go to a specific parent directory in eshell.
Argument MATCH a string that identifies the parent directory to go
to.

(fn &optional MATCH)" t)
(autoload 'eshell-up-peek "eshell-up" "\
Find a specific parent directory in eshell.
Argument MATCH a string that identifies the parent directory to find

(fn &optional MATCH)" t)
(register-definition-prefixes "eshell-up" '("eshell-up-"))


;;; Generated autoloads from exec-path-from-shell.el

(autoload 'exec-path-from-shell-copy-envs "exec-path-from-shell" "\
Set the environment variables with NAMES from the user's shell.

As a special case, if the variable is $PATH, then `exec-path' and
`eshell-path-env' are also set appropriately.  The result is an alist,
as described by `exec-path-from-shell-getenvs'.

(fn NAMES)")
(autoload 'exec-path-from-shell-copy-env "exec-path-from-shell" "\
Set the environment variable $NAME from the user's shell.

As a special case, if the variable is $PATH, then `exec-path' and
`eshell-path-env' are also set appropriately.  Return the value
of the environment variable.

(fn NAME)" t)
(autoload 'exec-path-from-shell-initialize "exec-path-from-shell" "\
Initialize environment from the user's shell.

The values of all the environment variables named in
`exec-path-from-shell-variables' are set from the corresponding
values used in the user's shell." t)
(register-definition-prefixes "exec-path-from-shell" '("exec-path-from-shell-"))

;;; End of scraped data

(provide 'aweshell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; aweshell-autoloads.el ends here
